name: Sync Bot Data to GitHub

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Commit and push data files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add users_data.json shop.json
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Sync bot data [skip ci]"
          git push https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
